#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_ICON1                               100
#define IDD_MAINDIALOG                          102
#define IDD_INFO                                104
#define IDD_CONFIG                              106
#define IDD_SEQ                                 108
#define IDD_MIDI_CONFIG                         109
#define IDC_EDIT1                               1000
#define IDC_FILE                                1000
#define IDC_MIN_MAX_LATENCY                     1000
#define IDC_VIDEO                               1000
#define IDC_LATENCY                             1001
#define IDC_MIDI_OUTPUT_DEVICE                  1001
#define IDC_SLIDER                              1001
#define IDC_CHANNEL                             1002
#define IDC_EDIT2                               1002
#define IDC_MIDI_INPUT_DEVICE                   1002
#define IDC_WAVEFORM                            1002
#define IDC_APPLY                               1003
#define IDC_EDIT3                               1003
#define IDC_INFO                                1003
#define IDC_MIDI_INFO                           1003
#define IDC_EDIT4                               1004
#define IDC_INPUT_CHANNEL                       1004
#define IDC_MIDI_CONFIG_APPLY                   1004
#define IDC_EVENT_MODE                          1005
#define IDC_PLAY                                1005
#define IDC_SEQ_AREA                            1005
#define IDC_REPEAT_CHECK                        1006
#define IDC_PAUSE                               1007
#define IDC_EXC_MODE                            1008
#define IDC_STOP                                1009
#define IDC_TAB                                 1011
#define IDC_ENDPOINT_DEVICE                     1017
#define IDC_SAMPLE_BIT                          1018
#define IDC_VALID_SAMPLE_BITS                   1019
#define IDC_SAMPLE_RATE                         1020
#define IDC_CANCEL                              40000
#define IDS_STRING1                             40000
#define IDC_INPUT_ENDPOINT_DEVICE               40010
#define IDC_INPUT_SAMPLE_BIT                    40011
#define IDC_INPUT_VALID_SAMPLE_BITS             40012
#define IDC_INPUT_EXC_MODE                      40014
#define IDC_INPUT_EVENT_MODE                    40015
#define IDC_INPUT_SAMPLE_RATE                   40017
#define IDC_INPUT_LATENCY                       40018
#define IDC_INPUT_MIN_MAX_LATENCY               40019
